### ISSUE TITLE
Licenciamento

### ISSUE THREAD

**Issue by ldemattos** [resristow/atp-equi#5]
Olá, @resristow !

Primeiramente obrigado por compartilhar o programa em questão. Estou precisando gerar alguns equivalentes para o ATP e estava prestes a desenvolver um programa semelhante ao seu =)

Em vez de desenvolver um programa novo, tentarei colaborar contigo caso haja necessidade de complementar alguma coisa. Eu ainda não o testei.

No entanto, peço que defina a licença do teu programa, caso contrário legalmente ninguém pode nem usar ou modificar seu programa sem o risco de ser processado - https://choosealicense.com/no-license/ . Seu arquivo LICENSE está vazio. Caso deseje que seu programa seja aberto/livre, sugiro que use alguma versão da GNU GPL, o que garante que seu código permanecerá para sempre livre e ninguém poderá se apropriar dele.

Mais uma vez, obrigado por compartilhar!

Atenciosamente,
LMNM

**Comment by resristow** [comment]
Olá, Leonardo!
Nunca tinha pensado sobre licença! Obrigado por trazer à luz essa questão. Depois de ler um pouco, decidi pelo GPL. Acrescentei um cabeçalho no arquivo com o código e copiei a licença no arquivo LICENSE.
Espero que esteja tudo OK!
O programa me ajuda bastante. Posso te mandar um caso de um estudo real que usei faz algumas semanas.
Abraço!
